import Head from 'next/head';
import Link from 'next/link';
import { FaCanadianMapleLeaf } from 'react-icons/fa';

export default function Home() {
    return (
        <> 
            <Head>
                <title>Hike the North</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="absolute right-0 w-full min-h-screen md:p-[100px] flex justify-between items-center bg-black text-white z-5">                
                <video 
                    muted 
                    loop 
                    autoPlay
                    src="/assets/video/video.mp4" type="video/mp4"
                    className="absolute top-0 left-0 w-full h-full md:object-cover object-fill"
                ></video>                

                <div className="title relative z-10 pb-12 flex flex-col opacity-100 px-8 sm:px-0 mx-auto sm:mx-0">
                    <h1 className="flex text-7xl sm:text-8xl uppercase font-['Alfa_Slab_One']">
                        Hike 
                        <FaCanadianMapleLeaf className="text-white z-10 scale-[0.8]" />
                    </h1>
                    <h1 className="text-7xl italic pb-3">the</h1>
                    <h1 className="text-7xl sm:text-8xl uppercase font-['Alfa_Slab_One']">North</h1>
                    <Link href="/arrival"><a className='mx-auto sm:mx-0'><button className="text-xl sm:text-3xl text-white/100 font-semibold py-3 px-8 border outline outline-offset-3 outline-3 border-white tracking-wide mt-10 hover:scale-[1.02] ease-in duration-200">Explore the wilderness</button></a></Link>
                </div>
            </main>
        </>        
    )
}
